#!/usr/bin/env python3
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SETTINGS = Path.home() / ".claude" / "settings.json"
IS_WINDOWS = sys.platform == "win32"

STATUSLINE_SH = ROOT / "scripts" / "claude_quota_statusline.sh"
STATUSLINE_PS1 = ROOT / "scripts" / "claude_quota_statusline.ps1"
WRAPPER_SH = Path.home() / ".claude" / "cctokmon-bridge.sh"
WRAPPER_PS1 = Path.home() / ".claude" / "cctokmon-bridge.ps1"


def wrapper_sh_content() -> str:
    # 包一層 wrapper，避免 Claude Code statusLine 用 sh -c 執行時，
    # 帶空格與中文的專案路徑被 shell 切壞導致 bridge 從未被呼叫。
    return (
        "#!/usr/bin/env bash\n"
        "# Auto-generated by install_claude_quota_bridge.py — do not edit.\n"
        f'exec "{STATUSLINE_SH}" "$@"\n'
    )


def wrapper_ps1_content() -> str:
    # 同樣道理：包一層固定路徑的 wrapper，避免帶空格／中文的專案路徑
    # 被 statusLine 指令字串切壞；用 & 呼叫即可沿用同一個 powershell.exe 行程的 stdin。
    return (
        "# Auto-generated by install_claude_quota_bridge.py - do not edit.\n"
        f'& "{STATUSLINE_PS1}" @args\n'
    )


def write_wrapper_unix() -> None:
    WRAPPER_SH.parent.mkdir(parents=True, exist_ok=True)
    desired = wrapper_sh_content()
    if not WRAPPER_SH.exists() or WRAPPER_SH.read_text(encoding="utf-8") != desired:
        WRAPPER_SH.write_text(desired, encoding="utf-8")
    WRAPPER_SH.chmod(0o755)


def write_wrapper_windows() -> None:
    WRAPPER_PS1.parent.mkdir(parents=True, exist_ok=True)
    desired = wrapper_ps1_content()
    if not WRAPPER_PS1.exists() or WRAPPER_PS1.read_text(encoding="utf-8") != desired:
        WRAPPER_PS1.write_text(desired, encoding="utf-8")


def statusline_config() -> dict:
    if IS_WINDOWS:
        return {
            "type": "command",
            "command": f'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "{WRAPPER_PS1}"',
            "padding": 1,
            "refreshInterval": 60,
        }
    return {
        "type": "command",
        "command": str(WRAPPER_SH),
        "padding": 1,
        "refreshInterval": 60,
    }


def main() -> None:
    SETTINGS.parent.mkdir(parents=True, exist_ok=True)
    if IS_WINDOWS:
        write_wrapper_windows()
    else:
        write_wrapper_unix()

    if SETTINGS.exists():
        try:
            data = json.loads(SETTINGS.read_text(encoding="utf-8"))
        except Exception:
            data = {}
    else:
        data = {}

    if data.get("statusLine") != statusline_config():
        data["statusLine"] = statusline_config()
        SETTINGS.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
