#!/usr/bin/env python3
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SETTINGS = Path.home() / ".claude" / "settings.json"
STATUSLINE = ROOT / "scripts" / "claude_quota_statusline.sh"
WRAPPER = Path.home() / ".claude" / "cctokmon-bridge.sh"


def wrapper_content() -> str:
    # 包一層 wrapper，避免 Claude Code statusLine 用 sh -c 執行時，
    # 帶空格與中文的專案路徑被 shell 切壞導致 bridge 從未被呼叫。
    return (
        "#!/usr/bin/env bash\n"
        "# Auto-generated by install_claude_quota_bridge.py — do not edit.\n"
        f'exec "{STATUSLINE}" "$@"\n'
    )


def write_wrapper() -> None:
    WRAPPER.parent.mkdir(parents=True, exist_ok=True)
    desired = wrapper_content()
    if not WRAPPER.exists() or WRAPPER.read_text() != desired:
        WRAPPER.write_text(desired)
    WRAPPER.chmod(0o755)


def statusline_config() -> dict:
    return {
        "type": "command",
        "command": str(WRAPPER),
        "padding": 1,
        "refreshInterval": 60,
    }


def main() -> None:
    SETTINGS.parent.mkdir(parents=True, exist_ok=True)
    write_wrapper()
    if SETTINGS.exists():
        try:
            data = json.loads(SETTINGS.read_text())
        except Exception:
            data = {}
    else:
        data = {}

    if data.get("statusLine") != statusline_config():
        data["statusLine"] = statusline_config()
        SETTINGS.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")


if __name__ == "__main__":
    main()
